# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import server_tools_pb2 as server__tools__pb2


class MnistServerStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.StartJobWait = channel.unary_unary(
        '/helloworld.MnistServer/StartJobWait',
        request_serializer=server__tools__pb2.DataMessage.SerializeToString,
        response_deserializer=server__tools__pb2.PredictionMessage.FromString,
        )
    self.StartJobNoWait = channel.unary_unary(
        '/helloworld.MnistServer/StartJobNoWait',
        request_serializer=server__tools__pb2.DataMessage.SerializeToString,
        response_deserializer=server__tools__pb2.IDMessage.FromString,
        )
    self.ProbeJob = channel.unary_unary(
        '/helloworld.MnistServer/ProbeJob',
        request_serializer=server__tools__pb2.IDMessage.SerializeToString,
        response_deserializer=server__tools__pb2.PredictionMessage.FromString,
        )
    self.RequestClientID = channel.unary_unary(
        '/helloworld.MnistServer/RequestClientID',
        request_serializer=server__tools__pb2.NullParam.SerializeToString,
        response_deserializer=server__tools__pb2.IDMessage.FromString,
        )


class MnistServerServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def StartJobWait(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def StartJobNoWait(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ProbeJob(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def RequestClientID(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_MnistServerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'StartJobWait': grpc.unary_unary_rpc_method_handler(
          servicer.StartJobWait,
          request_deserializer=server__tools__pb2.DataMessage.FromString,
          response_serializer=server__tools__pb2.PredictionMessage.SerializeToString,
      ),
      'StartJobNoWait': grpc.unary_unary_rpc_method_handler(
          servicer.StartJobNoWait,
          request_deserializer=server__tools__pb2.DataMessage.FromString,
          response_serializer=server__tools__pb2.IDMessage.SerializeToString,
      ),
      'ProbeJob': grpc.unary_unary_rpc_method_handler(
          servicer.ProbeJob,
          request_deserializer=server__tools__pb2.IDMessage.FromString,
          response_serializer=server__tools__pb2.PredictionMessage.SerializeToString,
      ),
      'RequestClientID': grpc.unary_unary_rpc_method_handler(
          servicer.RequestClientID,
          request_deserializer=server__tools__pb2.NullParam.FromString,
          response_serializer=server__tools__pb2.IDMessage.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'helloworld.MnistServer', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
